### PR TITLE
Add sponsor logo for x-ion

### PR DESCRIPTION
**Pull request by skrings**
PTAL @janz93 or @emrox

### CODE REVIEW

**Comment by emrox** [comment]
@skrings I've changed the code a bit to the variant I've used on the 2018 page because the logos were not centered. If this variant is ok for you feel free to merge. Otherwise let me know and I can change it or feel free to adapt.

**Comment by emrox** [comment]
Your variant:
Ruby Unconf Hamburg 2019 | Ruby Unconf Hamburg 2019 will happen on 25th and 26th of May 2019 at the HAW Hamburg, DMI Campus Fin… 2019-03-14 21-04-19

Current variant:
Ruby Unconf Hamburg 2019 | Ruby Unconf Hamburg 2019 will happen on 25th and 26th of May 2019 at the HAW Hamburg, DMI Campus Fin… 2019-03-14 21-05-21

**Comment by emrox** [comment]
damn I have to fix the stylesheet for smaller screens (I'll do this in a separate MR in the next days)

**Comment by skrings** [comment]
@emrox Thanks for jumping in.

Please keep the links as markup (not markdown) in order to use CSS classes.

**Comment by skrings** [comment]
I reverted the refactoring in order to get the branch in a mergeable state as I would like to get the sponsor logo on our website.

@emrox You are very welcome to refactor the positioning of sponsor logos, please do this in a dedicated pull request to maintain the scope of this pull request.

**Pull request merged**
