### PR TITLE
Move ticket direct link into tito widget

### PR DESCRIPTION
**Pull request by skrings**
in order to replace the link on widget load.

PTAL @janz93 or @emrox

### CODE REVIEW

**Comment by emrox** [comment]
this way the link is not visible anymore which was the intention to have it under the widget - so people can go to the Tito page without using the widget (or just copy the link to the Tito page)

**Comment by skrings** [comment]
@emrox From my point of view the intention of the link is to make our ticket sales accessible for people who block external javascript e.g. from tito so the widget does not show up.

Also we will have a more prominent ticket link in the main menu.

If it works, it works 👍

**Comment by emrox** [comment]
see https://github.com/rubyunconfeu/2019-website/pull/11

> and make it more obvious

**Comment by skrings** [comment]
> Also we will have a more prominent ticket link in the main menu.

And here we go #21

**Comment by skrings** [comment]
As the website menu landed in master we can merge this pull request now. 👍

**Pull request merged**
