### PR TITLE
Add target blank and rel noopener to sponsor links

### PR DESCRIPTION
**Pull request by skrings**
PTAL @janz93 or @emrox

### CODE REVIEW

**Comment by emrox** [comment]
please don't force push on a already pushed branch, makes our all life more difficult

**Comment by emrox** [comment]
also I'm pro removing `rel="_blank"` in general because the user can self decide if one would like to open the link normal or in a new tab/window

 but I'm against adding it again with a external gem again because someone not used to will easily overlook it (and the user should be able to decide how to open it)

**Comment by skrings** [comment]
@emrox I needed to resolve the conflicts and force pushed *with lease* in order to make the branch mergeable again - so everything fine 😄

Regarding your question should we add `target="_blank"` to external links or not. This is something I am not changing with this pull request, the behavior stays the same. I just add `target="_blank"` with the gem instead of manually in the markup. My goal is to add `rel=noopener` to all external links because this is security relevant.

Please address the question pro or contra `target="_blank"` in a dedicated issue / pull request. If we change our mind and want to remove `target="_blank"` this can be done by changing the gem configuration and you can still override it in your markup 🚀

**Comment by skrings** [comment]
I have the impression that we will not be able to merge it until we get a shared understanding which external links should be opened in which way. Here is my proposal, we can apply the `target=blank` and `rel=noopener` rule only for the sponsor links selected by the css class. This way the external links get the `rel=noopener` attribute and all other links open the current context and therefore `rel=noopener` is not necessary. This feels like best of both worlds.

**Comment by emrox** [comment]
To clarify my last comment (and down vote): introducing this gem would be OK if we would just use Markdown. Since our links are in HTML we should keep the attributes in the HTML code to avoid confusion by to much magic.

**Comment by skrings** [comment]
My observation is that not all sponsor links have a `target=blank` this is an inconsistent user experience and none of the external links have a `rel=noopener` which is a security implication, I am interested in the latter. There is room for improvement for external link handling, which I addressed with this pull request by adding a gem that handles it for us.

@emrox What is your proposal for a alternative solution in order to improve the situation and create a consistent user experience with secure external links while the editor don't have to care about details like the `rel` attribute?

**Comment by skrings** [comment]
Here are some links that explain why you should care about `rel=noopener`.

https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
https://mathiasbynens.github.io/rel-noopener/

Closing because we could not agree. 💔

**Pull request closed without merging**
