### PR TITLE
Blogpost: Unconf explained

### PR DESCRIPTION
**Pull request by p0wl**
Intention: Explain Unconf in detail for first time participants and inspire to give a talk

### CODE REVIEW

**Comment by skrings** [comment]
This already looks very good @p0wl. As a further improvement you could add a little FAQ inspired by the questions we received via mail.

* Which kind of session formats are possible?
* Is there a call for papers as it is known from other conferences?
* As a first time speaker should I attend and propose a topic?
* As an experienced speaker should I propose a talk?
* If I propose a talk will I definitely get the chance to present it?

**Comment by skrings** [comment]
You could use a picture from last years voting https://photos.google.com/share/AF1QipMsEs4aQYcFM8huSV0wCqM9Ad8QUOThI8OLZ-i_25YpcQIWNQ3GUGs6AmKU4n_syw/photo/AF1QipMHzGrQcK3XB7m2Zgx6vOrpytIjW8RcwYpy14uM?key=akdDRURtREoySXRveVFlcmlkUVVENHRkOWN4Yy13

**Comment by skrings** [comment]
And please add a link to our ticket sales: https://ti.to/ruby-unconf/2019

**Comment by p0wl** [comment]
PTAL =)

**Review by skrings — APPROVED** [review]
Awesome @p0wl 🍨

**Pull request merged**
