### PR TITLE
Add menu to website

### PR DESCRIPTION
**Pull request by skrings**
In order to have important sections like `Tickets` easily accessible. We might add more menu items in the future, e.g. `Blog` and `Sponsors`.

PTAL @janz93 or @emrox

### CODE REVIEW

**Comment by emrox** [comment]
maybe make it sticky? so when scrolling down the header stays on top

**Comment by skrings** [comment]
Thanks for sharing your idea, I like it.

At the same time I am a fan of:
> Make it work. Make it pretty.

I would like to focus on getting the menu out in order to improve the website. Iterating on the design and replacing the menu with something different can still be done afterwards.

**Comment by skrings** [comment]
As long there is no further feedback I would like to merge the Pull Request in order to improve the website.

**Comment by stefan-eventinc** [comment]
I'll have a look on it on the next days since I'm busy right now

**Comment by emrox** [comment]
can you improve the mobile layout?

Ruby Unconf Hamburg 2019 | Ruby Unconf Hamburg 2019 will happen on 25th and 26th of May 2019 at the HAW Hamburg, DMI Campus Fin… 2019-03-14 20-46-54

**Comment by skrings** [comment]
What do you mean by improve? What exactly should be changed from your point of view?

**Comment by emrox** [comment]
I just sketched an alternate variant: https://github.com/rubyunconfeu/2019-website/pull/24

I like the navigation on the [2019 jsconf page](https://2019.jsconf.eu) - at least the variant with the burger menu on mobile could be a good thing in the end

**Comment by skrings** [comment]
Ok I have changed the menu to fit better on smaller screens similar to your proposal.

On top of that I turned the ticket link into a call to action.

> I like the navigation on the 2019 jsconf page - at least the variant with the burger menu on mobile could be a good thing in the end

A hamburger menu on mobile is out of scope 😄

**Comment by skrings** [comment]
This is how it looks right now:

dinge

**Comment by skrings** [comment]
I am merging this pull request now in order to improve the website by adding the menu and make our ticket sales easier to reach. If there is something with this menu you would like to improve please start iterating and change it in the way you want. ❤️

**Pull request merged**
