### PR TITLE
Add old ticket layout

### PR DESCRIPTION
**Pull request by janz93**
remove the ti.to iframe and use the nice ticket boxes
see https://github.com/rughh/ruby-unconf-website/commit/94eb21fd382aff2f825047a4a0defa6fa0c25747

### CODE REVIEW

**Comment by Farson** [comment]
I don't like the old ticket layout. :(

**Comment by janz93** [comment]
Hmm :confused: but is a simple iframe better?
I personally would tend towards the old ticket boxes 😇 ^^

**Comment by skrings** [comment]
Hey @janz93 this seems dated - can we close this pull request?

**Comment by janz93** [comment]
Close as we couldn't agree.

**Pull request closed without merging**
