### PR TITLE
Childcare Blogpost

### PR DESCRIPTION
**Pull request by p0wl**
PTAL @skrings 

**wait for confirmation from kidsevent before merging this!**

### CODE REVIEW

**Comment by janz93** [comment]
Lgtm :ok_hand:

**Comment by skrings** [comment]
Great that you take care of this @p0wl. As a further improvement you could add a little FAQ with questions that might be important for parents.

* How many childcare professionals will take care of the kids?
* Will there be any catering for the kids during the day?
* Where is the childcare area located?

**Comment by p0wl** [comment]
PTAL

**Review by skrings — APPROVED** [review]
💯

**Pull request merged**
